
package com.admitone.utils;


public class ErrorCodes {

	public enum ADMITONE_HTTP_ERROR_CODES {
	    UNKNOWN_USER,
	    UNKNOWN_TENANT,
	    INVALID_TENANT,
	    TAMPERING_DETECTED,
	    UNEXPECTED_ERROR,
	    AUTHENTICATION_FAILED,
	    PASSWORD_EXPIRED,
	    ACCOUNT_EXPIRED,
	    ACCOUNT_LOCKED,
	    AUTHORIZATION_FAILED,
	    MAX_PASSWORD_FAILURES_REACHED,
	    DATABASE_ERROR,
	    REST_INTERFACE_DOES_NOT_EXIST,
	    SESSION_DOES_NOT_EXIST,
	    CYCLIC_DEPENDENCY,
        VALIDATION_ERROR,
        CONSTRAINT_VIOLATION
	}


}
